apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/lm-evaluation-harness?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "build/operator-nudging.yaml"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push"
      && target_branch == "rhoai-3.4-ea.2"
      && ( !".tekton/**".pathChanged() || ".tekton/odh-ta-lmes-job-v3-4-ea-2-push.yaml".pathChanged() )
  labels:
    appstudio.openshift.io/application: rhoai-v3-4-ea-2
    appstudio.openshift.io/component: odh-ta-lmes-job-v3-4-ea-2
    pipelines.appstudio.openshift.io/type: build
  name: odh-ta-lmes-job-v3-4-ea-2-on-push
  namespace: rhoai-tenant
spec:
  timeouts:
    pipeline: 8h
    tasks: 4h
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: additional-tags
    value:
    - '{{target_branch}}-{{revision}}'
  - name: output-image
    value: quay.io/rhoai/odh-ta-lmes-job-rhel9:{{target_branch}}
  - name: rhoai-version
    value: "3.4.0-ea.2"
  - name: dockerfile
    value: Dockerfile.konflux.lmes-job
  - name: path-context
    value: .
  - name: hermetic
    value: false
  - name: build-source-image
    value: true
  - name: build-image-index
    value: true
  - name: build-platforms
    value:
    - linux/x86_64
    - linux-m2xlarge/arm64
    - linux/ppc64le
    - linux/s390x
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/konflux-central.git
    - name: revision
      value: '{{ target_branch }}'
    - name: pathInRepo
      value: pipelines/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-odh-ta-lmes-job-v3-4-ea-2
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
